name: Release

on:
  # manual trigger
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependency
        run: yarn install

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
